# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField()),
                ('judul', models.CharField(max_length=30)),
                ('tahun_tayang', models.IntegerField()),
                ('musim_tayang', models.CharField(max_length=10)),
                ('jumlah_episode', models.IntegerField()),
                ('studio_pembuat', models.CharField(max_length=10)),
                ('adaptasi', models.CharField(max_length=10)),
                ('deskripsi', models.CharField(max_length=200)),
            ],
        ),
    ]
